<?php
    include_once('../resources/views/dashboard/modals/entretiens/entretiens.blade.php');
    include_once('../resources/views/dashboard/modals/bikesClients/bikesClients.blade.php');
    include_once('../resources/views/dashboard/modals/clientsAndProspects/clientsAndProspects.blade.php');
    include_once('../resources/views/dashboard/modals/clientsAndProspects/modifyCompany/modifyCompany.blade.php');
    include_once('../resources/views/dashboard/modals/clientsAndProspects/addClient/addClient.blade.php');
    include_once('../resources/views/dashboard/modals/entretiens/addEntretien/addEntretien.blade.php');
    include_once('../resources/views/dashboard/modals/bikesClients/addBike/addBike.blade.php');
    include_once('../resources/views/dashboard/modals/clientsAndProspects/modifyCompany/addContactCompany/addContactCompany.blade.php');
    include_once('../resources/views/dashboard/modals/clientsAndProspects/modifyCompany/modifyContactCompany/modifyContactCompany.blade.php');
    include_once('../resources/views/dashboard/modals/clientsAndProspects/modifyCompany/deleteContactCompany/deleteContactCompany.blade.php');